server:
  port: 8092

spring:
  application:
    name: product-client
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8094
feign:
  sentinel:
    enabled: true
